/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * listThingItem.java
 *
 * Created on May 16, 2011, 6:35:16 AM
 */
package things.views;
import java.awt.Component;
import java.awt.event.MouseListener;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import things.models.Thing;
import things.sessions.User_session;


/**
 *
 * @author fauzan
 */
public class listThingItem extends javax.swing.JPanel implements ListCellRenderer {

    /** Creates new form listThingItem */
    private int value;
    private String Content;
   
    
    public listThingItem() {
      
        initComponents();
        
         
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemDetail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        itemDetail.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addGap(46, 46, 46)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(itemDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemDetail;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) { 
        listThingItem p = this;        
        Thing th = (Thing) value;
        String container = "<html>"
                    +"<div>"
                    +"<span style='color:green; font-weight:bold'>"
                    +th.getNote()+"</span><br/>"
                    +"<small>"
                    +th.getDue_time()
                    +"</small>"
                    +"</div>"
                    +"</html>";
       
        p.itemDetail.setText(container) ;
        p.value = th.getID();
        Option_action oa = new Option_action(this.value);
        if(isSelected){
            System.out.println("slected");
            oa.setVisible(true);
            list.clearSelection();
        }
        return p;
    }
   
   
}
