/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * thingsView.java
 *
 * Created on May 15, 2011, 5:48:43 PM
 */
package things.views;

import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import things.sessions.User_session;
import things.controllers.Things_Controller;
import things.models.Thing;


/**
 *
 * @author fauzan
 */
public class thingsView_1 extends javax.swing.JFrame  {
    private Things_Controller thing = new Things_Controller();
    private DefaultListModel listModel = new DefaultListModel();
    private addThing At = new addThing();
    listThingItem lti = new listThingItem();
   
    /** Creates new form thingsView */
    public thingsView_1() {
        initComponents();
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        userIdentity = new javax.swing.JLabel();
        mainLayer = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        highPriorityList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        normalPriorityList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        justRemindMePriorityList = new javax.swing.JList();
        viewButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        addThingButton = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        userIdentity.setFont(new java.awt.Font("Ubuntu", 1, 18));

        mainLayer.setPreferredSize(new java.awt.Dimension(366, 400));

        getHighPriorityThings();
        jScrollPane2.setViewportView(highPriorityList);

        jTabbedPane1.addTab("High Priority", jScrollPane2);

        getNormalPriorityThings();
        jScrollPane3.setViewportView(normalPriorityList);

        jTabbedPane1.addTab("Normal", jScrollPane3);

        getJustRemindMePriorityThings();
        jScrollPane4.setViewportView(justRemindMePriorityList);

        jTabbedPane1.addTab("Just Remind Me", jScrollPane4);

        viewButton.setText("View Plan");

        editButton.setText("Edit");

        logoutButton.setText("Logut");

        addThingButton.setText("Add plan");

        javax.swing.GroupLayout mainLayerLayout = new javax.swing.GroupLayout(mainLayer);
        mainLayer.setLayout(mainLayerLayout);
        mainLayerLayout.setHorizontalGroup(
            mainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayerLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayerLayout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addContainerGap())
                    .addGroup(mainLayerLayout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(viewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addThingButton)
                        .addGap(22, 22, 22))))
        );
        mainLayerLayout.setVerticalGroup(
            mainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addThingButton)
                    .addComponent(viewButton)
                    .addComponent(editButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIdentity)
                .addContainerGap(354, Short.MAX_VALUE))
            .addComponent(mainLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIdentity))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getHighPriorityThings(){
       
       
        for(Thing things : thing.getHighPriorityThings()){
            listModel.addElement(things);
            
        }
        
        highPriorityList.setModel(listModel); 
        highPriorityList.setCellRenderer(lti);
        
        
    }
   
    public void getNormalPriorityThings(){
        DefaultListModel listModel = new DefaultListModel();
        for(Thing things : thing.getNormalPriorityThings()){
             String container = "<html>"
                    +"<div style='width: 255px;' >"
                    +"<span style='color:green; font-weight:bold'>"
                    +things.getNote()+"</span><br/>"
                    +"<small>"
                    +things.getDue_time()
                    +"</small>"
                    +"<hr/>" 
                    +"</div>"
                    +"</html>";
            listModel.addElement(container);
        }
        
        normalPriorityList.setModel(listModel);
    }
    
    public void getJustRemindMePriorityThings(){
        DefaultListModel listModel = new DefaultListModel();
        for(Thing things : thing.getJustRemindMePriorityThings()){
             String container = "<html>"
                    +"<div style='width: 255px;' >"
                    +"<span style='color:green; font-weight:bold'>"
                    +things.getNote()+"</span><br/>"
                    +"<small>"
                    +things.getDue_time()
                    +"</small>"
                    +"<hr/>" 
                    +"</div>"
                    +"</html>";
            listModel.addElement(container);
        }
        justRemindMePriorityList.setModel(listModel);
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addThingButton;
    private javax.swing.JButton editButton;
    private javax.swing.JList highPriorityList;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList justRemindMePriorityList;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainLayer;
    private javax.swing.JList normalPriorityList;
    protected javax.swing.JLabel userIdentity;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
